SEED_WORDS = [
    {"ua": "привіт", "ru": "привет", "transcription": "[прывіт]", "example": "Привіт, як справи?", "category": "greetings"},
    {"ua": "добрий день", "ru": "добрый день", "transcription": "[добрий день]", "example": "Добрий день, пане!", "category": "greetings"},
    {"ua": "добрий ранок", "ru": "доброе утро", "transcription": "[добрий ранок]", "example": "Добрий ранок, як спалось?", "category": "greetings"},
    {"ua": "добрий вечір", "ru": "добрый вечер", "transcription": "[добрий вечір]", "example": "Добрий вечір, ласкаво просимо!", "category": "greetings"},
    {"ua": "дякую", "ru": "спасибо", "transcription": "[дякую]", "example": "Дякую за допомогу!", "category": "greetings"},
    {"ua": "будь ласка", "ru": "пожалуйста", "transcription": "[будь ласка]", "example": "Будь ласка, сідайте.", "category": "greetings"},
    {"ua": "вибачте", "ru": "извините", "transcription": "[выбачтэ]", "example": "Вибачте, де тут зупинка?", "category": "greetings"},
    {"ua": "так", "ru": "да", "transcription": "[так]", "example": "Так, я згоден.", "category": "greetings"},
    {"ua": "ні", "ru": "нет", "transcription": "[ні]", "example": "Ні, дякую.", "category": "greetings"},
    {"ua": "добре", "ru": "хорошо", "transcription": "[добрэ]", "example": "Добре, домовились!", "category": "greetings"},
    {"ua": "до побачення", "ru": "до свидания", "transcription": "[до побачення]", "example": "До побачення, гарного дня!", "category": "greetings"},

    {"ua": "хліб", "ru": "хлеб", "transcription": "[хліб]", "example": "Купи хліб, будь ласка.", "category": "food"},
    {"ua": "вода", "ru": "вода", "transcription": "[вода]", "example": "Дайте склянку води.", "category": "food"},
    {"ua": "молоко", "ru": "молоко", "transcription": "[молоко]", "example": "Молоко свіже і смачне.", "category": "food"},
    {"ua": "м'ясо", "ru": "мясо", "transcription": "[мйасо]", "example": "Сьогодні на обід м'ясо.", "category": "food"},
    {"ua": "овочі", "ru": "овощи", "transcription": "[овочі]", "example": "Свіжі овочі з ринку.", "category": "food"},
    {"ua": "фрукти", "ru": "фрукты", "transcription": "[фрукты]", "example": "Я люблю свіжі фрукти.", "category": "food"},
    {"ua": "кава", "ru": "кофе", "transcription": "[кава]", "example": "Зроби мені каву, будь ласка.", "category": "food"},
    {"ua": "чай", "ru": "чай", "transcription": "[чай]", "example": "Хочеш чаю з лимоном?", "category": "food"},
    {"ua": "сніданок", "ru": "завтрак", "transcription": "[сніданок]", "example": "На сніданок я їм кашу.", "category": "food"},
    {"ua": "обід", "ru": "обед", "transcription": "[обід]", "example": "Час обіду — перша година.", "category": "food"},
    {"ua": "вечеря", "ru": "ужин", "transcription": "[вэчэря]", "example": "Вечеря буде о сьомій.", "category": "food"},
    {"ua": "сіль", "ru": "соль", "transcription": "[сіль]", "example": "Передай сіль, будь ласка.", "category": "food"},
    {"ua": "цукор", "ru": "сахар", "transcription": "[цукор]", "example": "Скільки цукру в каву?", "category": "food"},
    {"ua": "масло", "ru": "масло", "transcription": "[масло]", "example": "Намаж масло на хліб.", "category": "food"},
    {"ua": "сир", "ru": "сыр", "transcription": "[сир]", "example": "Голландський сир дуже смачний.", "category": "food"},
    {"ua": "яйце", "ru": "яйцо", "transcription": "[яйцэ]", "example": "Звари яйце на сніданок.", "category": "food"},
    {"ua": "рис", "ru": "рис", "transcription": "[рис]", "example": "Рис з овочами — смачна страва.", "category": "food"},
    {"ua": "риба", "ru": "рыба", "transcription": "[рыба]", "example": "Свіжа риба з моря.", "category": "food"},
    {"ua": "картопля", "ru": "картошка", "transcription": "[картопля]", "example": "Смажена картопля — моя улюблена.", "category": "food"},
    {"ua": "суп", "ru": "суп", "transcription": "[суп]", "example": "Борщ — найсмачніший суп.", "category": "food"},

    {"ua": "машина", "ru": "машина", "transcription": "[машына]", "example": "Машина стоїть біля дому.", "category": "transport"},
    {"ua": "автобус", "ru": "автобус", "transcription": "[автобус]", "example": "Автобус приїде за 5 хвилин.", "category": "transport"},
    {"ua": "потяг", "ru": "поезд", "transcription": "[потяг]", "example": "Потяг до Львова о 9 ранку.", "category": "transport"},
    {"ua": "зупинка", "ru": "остановка", "transcription": "[зупынка]", "example": "Де найближча зупинка?", "category": "transport"},
    {"ua": "квиток", "ru": "билет", "transcription": "[квыток]", "example": "Квиток коштує 20 гривень.", "category": "transport"},
    {"ua": "дорога", "ru": "дорога", "transcription": "[дорога]", "example": "Дорога до міста зайняла годину.", "category": "transport"},
    {"ua": "літак", "ru": "самолёт", "transcription": "[літак]", "example": "Літак вилітає о третій.", "category": "transport"},
    {"ua": "таксі", "ru": "такси", "transcription": "[таксі]", "example": "Викличте мені таксі.", "category": "transport"},
    {"ua": "метро", "ru": "метро", "transcription": "[мэтро]", "example": "Я їду на метро.", "category": "transport"},
    {"ua": "велосипед", "ru": "велосипед", "transcription": "[вэлосыпэд]", "example": "Я катаюсь на велосипеді.", "category": "transport"},
    {"ua": "вулиця", "ru": "улица", "transcription": "[вулыця]", "example": "Ця вулиця дуже гарна.", "category": "transport"},
    {"ua": "міст", "ru": "мост", "transcription": "[міст]", "example": "Перейдіть через міст.", "category": "transport"},
    {"ua": "аеропорт", "ru": "аэропорт", "transcription": "[аеропорт]", "example": "Аеропорт далеко від центру.", "category": "transport"},
    {"ua": "вокзал", "ru": "вокзал", "transcription": "[вокзал]", "example": "Зустрінемось на вокзалі.", "category": "transport"},
    {"ua": "порт", "ru": "порт", "transcription": "[порт]", "example": "Одеський порт — найбільший.", "category": "transport"},

    {"ua": "один", "ru": "один", "transcription": "[одын]", "example": "Один квиток, будь ласка.", "category": "numbers"},
    {"ua": "два", "ru": "два", "transcription": "[два]", "example": "Два квитки на поїзд.", "category": "numbers"},
    {"ua": "три", "ru": "три", "transcription": "[тры]", "example": "Три дні відпочинку.", "category": "numbers"},
    {"ua": "чотири", "ru": "четыре", "transcription": "[чотыры]", "example": "Чотири сезони року.", "category": "numbers"},
    {"ua": "п'ять", "ru": "пять", "transcription": "[пйать]", "example": "П'ять хвилин до зустрічі.", "category": "numbers"},
    {"ua": "шість", "ru": "шесть", "transcription": "[шість]", "example": "Шість годин дороги.", "category": "numbers"},
    {"ua": "сім", "ru": "семь", "transcription": "[сім]", "example": "Сім днів на тиждень.", "category": "numbers"},
    {"ua": "вісім", "ru": "восемь", "transcription": "[вісім]", "example": "Вісім уроків сьогодні.", "category": "numbers"},
    {"ua": "дев'ять", "ru": "девять", "transcription": "[дэвйать]", "example": "Зустріч о дев'ятій ранку.", "category": "numbers"},
    {"ua": "десять", "ru": "десять", "transcription": "[дэсять]", "example": "Десять гривень за квиток.", "category": "numbers"},
    {"ua": "двадцять", "ru": "двадцать", "transcription": "[двадцять]", "example": "Двадцять хвилин пішки.", "category": "numbers"},
    {"ua": "сто", "ru": "сто", "transcription": "[сто]", "example": "Сто гривень за обід.", "category": "numbers"},

    {"ua": "понеділок", "ru": "понедельник", "transcription": "[понэділок]", "example": "Понеділок — перший день тижня.", "category": "days_months"},
    {"ua": "вівторок", "ru": "вторник", "transcription": "[вівторок]", "example": "У вівторок маємо зустріч.", "category": "days_months"},
    {"ua": "середа", "ru": "среда", "transcription": "[сэрэда]", "example": "Середа — середина тижня.", "category": "days_months"},
    {"ua": "четвер", "ru": "четверг", "transcription": "[чэтвэр]", "example": "У четвер іду до лікаря.", "category": "days_months"},
    {"ua": "п'ятниця", "ru": "пятница", "transcription": "[пйатныця]", "example": "П'ятниця — найкращий день!", "category": "days_months"},
    {"ua": "субота", "ru": "суббота", "transcription": "[субота]", "example": "У суботу відпочиваємо.", "category": "days_months"},
    {"ua": "неділя", "ru": "воскресенье", "transcription": "[нэділя]", "example": "Неділя — вихідний день.", "category": "days_months"},
    {"ua": "січень", "ru": "январь", "transcription": "[січэнь]", "example": "Січень — холодний місяць.", "category": "days_months"},
    {"ua": "лютий", "ru": "февраль", "transcription": "[лютый]", "example": "Лютий — найкоротший місяць.", "category": "days_months"},
    {"ua": "березень", "ru": "март", "transcription": "[бэрэзэнь]", "example": "У березні починається весна.", "category": "days_months"},
    {"ua": "квітень", "ru": "апрель", "transcription": "[квітэнь]", "example": "У квітні цвітуть дерева.", "category": "days_months"},
    {"ua": "травень", "ru": "май", "transcription": "[травэнь]", "example": "Травень — чудовий місяць.", "category": "days_months"},
    {"ua": "червень", "ru": "июнь", "transcription": "[чэрвэнь]", "example": "У червні починається літо.", "category": "days_months"},
    {"ua": "липень", "ru": "июль", "transcription": "[лыпэнь]", "example": "Липень — найспекотніший.", "category": "days_months"},
    {"ua": "серпень", "ru": "август", "transcription": "[сэрпэнь]", "example": "У серпні збирають урожай.", "category": "days_months"},
    {"ua": "вересень", "ru": "сентябрь", "transcription": "[вэрэсэнь]", "example": "Вересень — початок навчання.", "category": "days_months"},
    {"ua": "жовтень", "ru": "октябрь", "transcription": "[жовтэнь]", "example": "У жовтні падає листя.", "category": "days_months"},
    {"ua": "листопад", "ru": "ноябрь", "transcription": "[лыстопад]", "example": "Листопад — сірий місяць.", "category": "days_months"},
    {"ua": "грудень", "ru": "декабрь", "transcription": "[грудэнь]", "example": "У грудні святкуємо Новий рік.", "category": "days_months"},

    {"ua": "скільки коштує", "ru": "сколько стоит", "transcription": "[скількы коштуе]", "example": "Скільки коштує ця сукня?", "category": "phrases"},
    {"ua": "де знаходиться", "ru": "где находится", "transcription": "[дэ знаходыться]", "example": "Де знаходиться аптека?", "category": "phrases"},
    {"ua": "я не розумію", "ru": "я не понимаю", "transcription": "[я нэ розумію]", "example": "Вибачте, я не розумію.", "category": "phrases"},
    {"ua": "повторіть, будь ласка", "ru": "повторите, пожалуйста", "transcription": "[повторіть будь ласка]", "example": "Повторіть, будь ласка, повільніше.", "category": "phrases"},
    {"ua": "як справи", "ru": "как дела", "transcription": "[як справы]", "example": "Привіт! Як справи?", "category": "phrases"},
    {"ua": "мене звати", "ru": "меня зовут", "transcription": "[мэнэ зваты]", "example": "Мене звати Олександр.", "category": "phrases"},
    {"ua": "я хочу", "ru": "я хочу", "transcription": "[я хочу]", "example": "Я хочу замовити каву.", "category": "phrases"},
    {"ua": "можна", "ru": "можно", "transcription": "[можна]", "example": "Можна рахунок, будь ласка?", "category": "phrases"},
    {"ua": "допоможіть", "ru": "помогите", "transcription": "[допоможіть]", "example": "Допоможіть мені, будь ласка!", "category": "phrases"},
    {"ua": "я згоден", "ru": "я согласен", "transcription": "[я згодэн]", "example": "Так, я згоден з вами.", "category": "phrases"},
    {"ua": "зачекайте", "ru": "подождите", "transcription": "[зачэкайтэ]", "example": "Зачекайте хвилинку.", "category": "phrases"},
    {"ua": "я шукаю", "ru": "я ищу", "transcription": "[я шукаю]", "example": "Я шукаю готель.", "category": "phrases"},
    {"ua": "мені потрібно", "ru": "мне нужно", "transcription": "[мэні потрібно]", "example": "Мені потрібно до центру.", "category": "phrases"},
    {"ua": "я загубився", "ru": "я заблудился", "transcription": "[я загубывся]", "example": "Вибачте, я загубився.", "category": "phrases"},
    {"ua": "чудово", "ru": "отлично", "transcription": "[чудово]", "example": "Чудово! Домовились!", "category": "phrases"},
    {"ua": "смачного", "ru": "приятного аппетита", "transcription": "[смачного]", "example": "Смачного! Їжте на здоров'я.", "category": "phrases"},
    {"ua": "на здоров'я", "ru": "на здоровье / пожалуйста", "transcription": "[на здоровйа]", "example": "Дякую! — На здоров'я!", "category": "phrases"},
    {"ua": "я люблю", "ru": "я люблю", "transcription": "[я люблю]", "example": "Я люблю українську мову.", "category": "phrases"},
    {"ua": "до зустрічі", "ru": "до встречи", "transcription": "[до зустрічі]", "example": "До зустрічі завтра!", "category": "phrases"},
    {"ua": "все добре", "ru": "всё хорошо", "transcription": "[всэ добрэ]", "example": "Не хвилюйся, все добре.", "category": "phrases"},
]


async def seed_user_vocabulary(user_id: int) -> int:
    from bot.db.base import async_session
    from bot.db.repositories import VocabularyRepository

    async with async_session() as session:
        repo = VocabularyRepository(session)
        count = 0
        for word_data in SEED_WORDS:
            await repo.add_word(
                user_id=user_id,
                word_ua=word_data["ua"],
                word_ru=word_data["ru"],
                transcription=word_data.get("transcription"),
                example_ua=word_data.get("example"),
                category=word_data.get("category"),
            )
            count += 1
    return count
